=== sandrus88/xml-json-campus/src/main/resources/xsd/schema-online-campus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.sg.com" targetNamespace="http://www.sg.com"
	elementFormDefault="qualified">

	<xs:element name="campus" type="campusListType" />

	<xs:complexType name="campusListType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="students" type="studentListType" />
			<xs:element name="courses" type="coursesListType" />
			<xs:element name="topics" type="topicsListType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="studentListType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="student" type="studentType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="studentType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="surname" type="xs:string" />
			<xs:element name="jobTitle" type="xs:string" minOccurs="0" />
			<xs:element name="paymentType" type="paymentTypeType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:simpleType name="paymentTypeType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="OK" />
			<xs:enumeration value="NOTOK" />
			<xs:enumeration value="UNKNOWN" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="coursesListType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="course" type="courseType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="courseType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="description" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"/>
	</xs:complexType>

	<xs:complexType name="topicsListType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="topic" type="topicType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="topicType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="course" type="xs:integer"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"/>
	</xs:complexType>
</xs:schema>

=== sandrus88/xml-json-campus/src/test/resources/test_campus_data_backup.xml
<campus xmlns="http://www.sg.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sg.com ../xsd/schema-online-campus.xsd">

    <students>
        <student id="101">
            <name>Sandro</name>
            <surname>Gargano</surname>
            <jobTitle>Waiter</jobTitle>
            <paymentType>NOTOK</paymentType>
        </student>
        <student id="102">
            <name>Ermal</name>
            <surname>Aliraj</surname>
            <paymentType>OK</paymentType>
        </student>
	</students>
    <courses>
        <course id="201">
            <name>Java fundamentals</name>
        </course>
        <course id="203">
            <name>Operating Systems</name>
            <description>This course will introduce you to modern operating systems. We will focus on UNIX-based
                operating systems, though we will also learn about alternative operating systems, including Windows. The
                course will begin with an overview of the structure of modern operating systems. Over the course of the
                subsequent units, we will discuss the history of modern computers, analyze in detail each of the major
                components of an operating system (from processes to threads), and explore more advanced topics in the
                field, including memory management and file input/output. The class will conclude with a discussion of
                various system-related security issues.
            </description>
        </course>
    </courses>
    <topics>
        <topic id="301">
            <name>Objects Oriented Paradigm</name>
            <description>OOPS concepts (Data Abstraction, Encapsulation, Inheritance, Polymorphism)</description>
            <course>201</course>
        </topic>
        <topic id="302">
            <name>Basic Java constructs like loops and data types</name>
            <course>201</course>
        </topic>
    </topics>
</campus>

=== sandrus88/xml-json-campus/xml/campus_list.xml
<campus xmlns="http://www.sg.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sg.com ../xsd/schema-online-campus.xsd">

	<students>
		<student id="101">
			<name>Sandro</name>
			<surname>Gargano</surname>
			<jobTitle></jobTitle>
			<paymentType>NOTOK</paymentType>
		</student>
		<student id="102">
			<name>Ermal</name>
			<surname>Aliraj</surname>
			<jobTitle></jobTitle>
			<paymentType>OK</paymentType>
		</student>
		<student id="103">
			<name>Armela</name>
			<surname>Xhaxho</surname>
			<jobTitle></jobTitle>
			<paymentType>UNKNOWN</paymentType>
		</student>
		<student id="104">
			<name>Aida</name>
			<surname>Xhaxho</surname>
			<jobTitle></jobTitle>
			<paymentType>OK</paymentType>
		</student>
		<student id="101">
			<name>Andrea</name>
			<surname>Fumagalli</surname>
			<jobTitle></jobTitle>
			<paymentType>OK</paymentType>
		</student>
		<student id="101">
			<name>Alessandro</name>
			<surname>Eramo</surname>
			<jobTitle></jobTitle>
			<paymentType>UNKNOWN</paymentType>
		</student>
	</students>
	<courses>
		<course id="201">
			<name>Java fundamentals</name>
			<description></description>
		</course>
		<course id="202">
			<name>Java advanced programming</name>
			<description></description>
		</course>
		<course id="203">
			<name>Operating Systems</name>
			<description></description>
		</course>
		<course id="204">
			<name>Computer Network</name>
			<description></description>
		</course>
		<course id="205">
			<name>Data Structures and Algorithms</name>
			<description></description>
		</course>
	</courses>
	<topics>
		<topic id="301">
			<name>Objects Oriented Paradigm</name>
			<description>OOPS concepts (Data Abstraction, Encapsulation, Inheritance, Polymorphism)</description>
			<course>201</course>
		</topic>
		<topic id="302">
			<name>Basic Java constructs like loops and data types</name>
			<description></description>
			<course>201</course>
		</topic>
		<topic id="303">
			<name>String handling</name>
			<description></description>
			<course>201</course>
		</topic>
		<topic id="304">
			<name>Collection framework</name>
			<description></description>
			<course>201</course>
		</topic>
		<topic id="305">
			<name>Exception handling</name>
			<description></description>
			<course>201</course>
		</topic>
		<topic id="306">
			<name>Servlet</name>
			<description></description>
			<course>202</course>
		</topic>
		<topic id="307">
			<name>JSP</name>
			<description></description>
			<course>202</course>
		</topic>
		<topic id="308">
			<name>What is an Operating System?</name>
			<description></description>
			<course>203</course>
		</topic>
		<topic id="309">
			<name>Operating System history</name>
			<description></description>
			<course>203</course>
		</topic>
		<topic id="310">
			<name>Operating System concepts</name>
			<description></description>
			<course>203</course>
		</topic>
		<topic id="311">
			<name>Operating System structures</name>
			<description></description>
			<course>203</course>
		</topic>
		<topic id="312">
			<name>Local Area Network (LAN) Technologies</name>
			<description></description>
			<course>204</course>
		</topic>
		<topic id="313">
			<name>Introduction of MAC Address</name>
			<description></description>
			<course>204</course>
		</topic>
		<topic id="314">
			<name>Multiple Access Protocols</name>
			<description></description>
			<course>204</course>
		</topic>
		<topic id="315">
			<name>Ethernet Frame Format</name>
			<description></description>
			<course>204</course>
		</topic>
		<topic id="316">
			<name>Basic Data Structures: Arrays, Strings, Stacks, Queues</name>
			<description></description>
			<course>205</course>
		</topic>
		<topic id="317">
			<name>Basic math operations (addition, subtraction, multiplication, division, exponentiation)</name>
			<description></description>
			<course>205</course>
		</topic>
		<topic id="318">
			<name>Euclid's GCD Algorithm</name>
			<description></description>
			<course>205</course>
		</topic>
		<topic id="319">
			<name>Greedy Algorithms</name>
			<description></description>
			<course>205</course>
		</topic>
		<topic id="320">
			<name>Binary Searching</name>
			<description></description>
			<course>205</course>
		</topic>
	</topics>
</campus>

=== sandrus88/xml-json-campus/src/test/resources/test_campus2_data.xml
<campus xmlns="http://www.sg.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sg.com ../xsd/schema-online-campus.xsd">

    <students>
        <student id="101">
            <name>Sandro</name>
            <surname>Gargano</surname>
            <jobTitle>Waiter</jobTitle>
            <paymentType>NOTOK</paymentType>
        </student>
        <student id="102">
            <name>Ermal</name>
            <surname>Aliraj</surname>
            <paymentType>OK</paymentType>
        </student>
	</students>
</campus>
